import type { AnimationClip, Pose } from "./types";

const deg = (d: number) => (d * Math.PI) / 180;

function pose(
  root: { x: number; y: number },
  angles: Record<string, number>,
): Pose {
  return { root, angles };
}

const restAngles = {
  root: 0,
  head: deg(180),
  torso: 0,
  upperArmL: deg(55),
  forearmL: deg(-20),
  upperArmR: deg(-55),
  forearmR: deg(-20),
  thighL: deg(25),
  shinL: deg(15),
  thighR: deg(-25),
  shinR: deg(15),
};

/** Bundled stickman clip — run + trip seed for the editor/player. */
export const DEFAULT_CLIP: AnimationClip = {
  version: 1,
  durationMs: 3600,
  loop: true,
  viewBox: { w: 100, h: 120 },
  strokeWidth: 4,
  joints: [
    { id: "root", name: "Root", parentId: null, length: 0 },
    { id: "head", name: "Head", parentId: "root", length: 12 },
    { id: "torso", name: "Torso", parentId: "root", length: 26 },
    { id: "upperArmL", name: "Upper Arm L", parentId: "root", length: 13 },
    { id: "forearmL", name: "Forearm L", parentId: "upperArmL", length: 11 },
    { id: "upperArmR", name: "Upper Arm R", parentId: "root", length: 13 },
    { id: "forearmR", name: "Forearm R", parentId: "upperArmR", length: 11 },
    { id: "thighL", name: "Thigh L", parentId: "torso", length: 16 },
    { id: "shinL", name: "Shin L", parentId: "thighL", length: 14 },
    { id: "thighR", name: "Thigh R", parentId: "torso", length: 16 },
    { id: "shinR", name: "Shin R", parentId: "thighR", length: 14 },
  ],
  restPose: pose({ x: 50, y: 42 }, restAngles),
  keyframes: [
    {
      id: "kf-run-a",
      t: 0,
      pose: pose({ x: 50, y: 42 }, {
        ...restAngles,
        upperArmL: deg(60),
        forearmL: deg(-80),
        upperArmR: deg(-50),
        forearmR: deg(-90),
        thighL: deg(50),
        shinL: deg(90),
        thighR: deg(-30),
        shinR: deg(35),
      }),
    },
    {
      id: "kf-run-b",
      t: 0.12,
      pose: pose({ x: 52, y: 41 }, {
        ...restAngles,
        upperArmL: deg(-20),
        forearmL: deg(-50),
        upperArmR: deg(25),
        forearmR: deg(-60),
        thighL: deg(20),
        shinL: deg(100),
        thighR: deg(0),
        shinR: deg(5),
      }),
    },
    {
      id: "kf-run-c",
      t: 0.24,
      pose: pose({ x: 54, y: 42 }, {
        ...restAngles,
        upperArmL: deg(10),
        forearmL: deg(-15),
        upperArmR: deg(-55),
        forearmR: deg(-90),
        thighL: deg(0),
        shinL: deg(8),
        thighR: deg(-85),
        shinR: deg(95),
      }),
    },
    {
      id: "kf-run-d",
      t: 0.36,
      pose: pose({ x: 50, y: 42 }, {
        ...restAngles,
        upperArmL: deg(55),
        forearmL: deg(-85),
        upperArmR: deg(-55),
        forearmR: deg(-95),
        thighL: deg(45),
        shinL: deg(20),
        thighR: deg(-40),
        shinR: deg(50),
      }),
    },
    {
      id: "kf-trip",
      t: 0.48,
      pose: pose({ x: 58, y: 46 }, {
        ...restAngles,
        root: deg(20),
        head: deg(180),
        upperArmL: deg(-95),
        forearmL: deg(-5),
        upperArmR: deg(-100),
        forearmR: deg(-8),
        thighL: deg(30),
        shinL: deg(15),
        thighR: deg(-20),
        shinR: deg(18),
      }),
    },
    {
      id: "kf-fall",
      t: 0.62,
      pose: pose({ x: 68, y: 72 }, {
        ...restAngles,
        root: deg(85),
        head: deg(160),
        upperArmL: deg(110),
        forearmL: deg(-50),
        upperArmR: deg(-80),
        forearmR: deg(-100),
        thighL: deg(40),
        shinL: deg(80),
        thighR: deg(-30),
        shinR: deg(90),
      }),
    },
    {
      id: "kf-down",
      t: 0.75,
      pose: pose({ x: 70, y: 78 }, {
        ...restAngles,
        root: deg(95),
        head: deg(150),
        upperArmL: deg(115),
        forearmL: deg(-60),
        upperArmR: deg(-85),
        forearmR: deg(-80),
        thighL: deg(35),
        shinL: deg(85),
        thighR: deg(-25),
        shinR: deg(90),
      }),
    },
    {
      id: "kf-up",
      t: 0.9,
      pose: pose({ x: 55, y: 50 }, {
        ...restAngles,
        root: deg(15),
        upperArmL: deg(30),
        forearmL: deg(-40),
        upperArmR: deg(-20),
        forearmR: deg(-40),
        thighL: deg(15),
        shinL: deg(30),
        thighR: deg(-10),
        shinR: deg(25),
      }),
    },
  ],
};
